// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: w64Lj4qzFKznSdSZRXYR8
// Component: PTHYoU41i1gM
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { ParallaxWrapper } from "@plasmicpkgs/react-scroll-parallax"; // plasmic-import: bozP4lLlAZ/codeComponent
import Button2 from "../../Button2"; // plasmic-import: 7DC_s_ptcnZ/component
import { Iframe } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: CMDBvOhaI4s/codeComponent
import { PlasmicHead } from "@plasmicapp/react-web"; // plasmic-import: 4r5QdyDGcw/codeComponent
import { useScreenVariants as useScreenVariantsaNbDamBvYs } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: aNB-damBV_-ys/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_razorpay_payment_gateway.module.css"; // plasmic-import: w64Lj4qzFKznSdSZRXYR8/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: PTHYoU41i1gM/css
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: f7etD36KEfF/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: QUAkMH_X8-L/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: u5rY5asasG/icon
import imageBr23KcsoImAs from "./images/image.svg"; // plasmic-import: Br23kcsoImAS/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsaNbDamBvYs()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <ParallaxWrapper
            data-plasmic-name={"scrollParallax"}
            data-plasmic-override={overrides.scrollParallax}
            className={classNames("__wab_instance", sty.scrollParallax)}
            speed={20}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__f5EMj)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qnmY6)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xoCHw)}
                >
                  <p.PlasmicImg
                    data-plasmic-name={"img"}
                    data-plasmic-override={overrides.img}
                    alt={""}
                    className={classNames(sty.img)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"40px"}
                    src={{
                      src: imageBr23KcsoImAs,
                      fullWidth: 150,
                      fullHeight: 150,
                      aspectRatio: 1
                    }}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__b0Hho)}
                  >
                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__mHkCk
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__kpOLu)}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__t5Hd3)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5IAll
                        )}
                      >
                        {"Services"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__ytKc9
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__yBc7J)}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__ikFTx)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__meVn
                        )}
                      >
                        {"Features"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__grXr
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___5PEsx
                          )}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__sJBm3)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0NIEo
                        )}
                      >
                        {"Company"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__omUjO
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__kBcT)}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__oiH1D)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fQsZa
                        )}
                      >
                        {"Contact"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__m1YEk
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__fe1Ni)}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__mxhzW)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yyNoD
                        )}
                      >
                        {"Log in"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__vNzLd
                      )}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__yGp4V)}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__f7Vmp)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6V3Z2
                        )}
                      >
                        {"Sign up"}
                      </div>
                    </Button2>
                  </p.Stack>

                  {false ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kslOi)}
                    >
                      <button
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames(
                          projectcss.all,
                          projectcss.button,
                          projectcss.__wab_text,
                          sty.button
                        )}
                      >
                        {"Sign up"}
                      </button>

                      {true ? (
                        <Button2
                          className={classNames(
                            "__wab_instance",
                            sty.button2__arnmw
                          )}
                          color={"clear"}
                          endIcon={
                            <Icon38Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__kl7O
                              )}
                              role={"img"}
                            />
                          }
                          startIcon={
                            <ChecksvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__jfTw8
                              )}
                              role={"img"}
                            />
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___5T3Sc
                            )}
                          >
                            {"Log in"}
                          </div>
                        </Button2>
                      ) : null}
                    </div>
                  ) : null}
                </p.Stack>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.freeBox__mQfGs)}>
                <div className={classNames(projectcss.all, sty.freeBox__npBgy)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kzPM
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <h1
                          data-plasmic-name={"h1"}
                          data-plasmic-override={overrides.h1}
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <h2
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h2,
                                  projectcss.__wab_text,
                                  sty.h2__dEren
                                )}
                              >
                                <React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{
                                      color: "#0D2366",
                                      fontWeight: 700
                                    }}
                                  >
                                    {"Get paid instantly"}
                                  </span>
                                  <React.Fragment>{"\n"}</React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{
                                      color: "#0D2366",
                                      fontWeight: 700
                                    }}
                                  >
                                    {"with"}
                                  </span>
                                  <React.Fragment>{""}</React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#0D2366" }}
                                  >
                                    {" "}
                                  </span>
                                  <React.Fragment>{""}</React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#0D6642" }}
                                  >
                                    {"Payment"}
                                  </span>
                                  <React.Fragment>{""}</React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#0D2366" }}
                                  >
                                    {" Links"}
                                  </span>
                                  <React.Fragment>{"\n"}</React.Fragment>
                                  {
                                    <h5
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.h5,
                                        projectcss.__wab_text,
                                        sty.h5__hmWFj
                                      )}
                                    >
                                      <React.Fragment>
                                        <React.Fragment>{""}</React.Fragment>
                                        {
                                          <h3
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.h3,
                                              projectcss.__wab_text,
                                              sty.h3__p9Js2
                                            )}
                                          >
                                            <React.Fragment>
                                              <React.Fragment>
                                                {""}
                                              </React.Fragment>
                                              {
                                                <h5
                                                  className={classNames(
                                                    projectcss.all,
                                                    projectcss.h5,
                                                    projectcss.__wab_text,
                                                    sty.h5__jOr
                                                  )}
                                                >
                                                  <React.Fragment>
                                                    <React.Fragment>
                                                      {""}
                                                    </React.Fragment>
                                                    {
                                                      <h2
                                                        className={classNames(
                                                          projectcss.all,
                                                          projectcss.h2,
                                                          projectcss.__wab_text,
                                                          sty.h2__mNl3F
                                                        )}
                                                      >
                                                        <React.Fragment>
                                                          <span
                                                            className={
                                                              "plasmic_default__all plasmic_default__span"
                                                            }
                                                            style={{
                                                              color: "#0D2366"
                                                            }}
                                                          >
                                                            {"-"}
                                                          </span>
                                                          <React.Fragment>
                                                            {"\n"}
                                                          </React.Fragment>
                                                          {
                                                            <h3
                                                              className={classNames(
                                                                projectcss.all,
                                                                projectcss.h3,
                                                                projectcss.__wab_text,
                                                                sty.h3__zGtNq
                                                              )}
                                                            >
                                                              <React.Fragment>
                                                                <span
                                                                  className={
                                                                    "plasmic_default__all plasmic_default__span"
                                                                  }
                                                                  style={{
                                                                    color:
                                                                      "#0D2366"
                                                                  }}
                                                                >
                                                                  {
                                                                    "Share payment link via an email, SMS, messenger, chatbot etc. and get paid immediately. Accepting payments from customers is now  a link away."
                                                                  }
                                                                </span>
                                                              </React.Fragment>
                                                            </h3>
                                                          }

                                                          <React.Fragment>
                                                            {""}
                                                          </React.Fragment>
                                                        </React.Fragment>
                                                      </h2>
                                                    }

                                                    <React.Fragment>
                                                      {""}
                                                    </React.Fragment>
                                                  </React.Fragment>
                                                </h5>
                                              }

                                              <React.Fragment>
                                                {""}
                                              </React.Fragment>
                                            </React.Fragment>
                                          </h3>
                                        }

                                        <React.Fragment>{""}</React.Fragment>
                                      </React.Fragment>
                                    </h5>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                </React.Fragment>
                              </h2>
                            }

                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </h1>
                      ) : null}
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>

                  {true ? (
                    <Button2
                      data-plasmic-name={"signUpNowButton"}
                      data-plasmic-override={overrides.signUpNowButton}
                      className={classNames(
                        "__wab_instance",
                        sty.signUpNowButton
                      )}
                      link={"https://razorpay.com/payment-links/"}
                      showEndIcon={true}
                      size={"compact"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ncNik
                        )}
                      >
                        {"Log in"}
                      </div>
                    </Button2>
                  ) : null}

                  <div
                    className={classNames(projectcss.all, sty.freeBox__whxpj)}
                  >
                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___7Gj6T
                        )}
                      >
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__miEs8)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ySxPh
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#515978" }}
                            >
                              {
                                "Collect faster payments on UPI Payment Links with upto 50% lower fees"
                              }
                            </span>
                          </React.Fragment>
                        </div>

                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__nwBzC
                          )}
                          href={"https://www.plasmic.app/"}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ textDecorationLine: "underline" }}
                            >
                              {"Know More"}
                            </span>
                          </React.Fragment>
                        </a>
                      </div>
                    ) : null}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___2CFyg)}
                  >
                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vPax
                        )}
                      >
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__yTuse)}
                          role={"img"}
                        />

                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__nYvq1
                          )}
                          href={"https://www.plasmic.app/"}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ textDecorationLine: "underline" }}
                            >
                              {"Know More"}
                            </span>
                          </React.Fragment>
                        </a>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xwlXz
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#515978" }}
                            >
                              {
                                "The all new powerful Payment Links with Reminders "
                              }
                            </span>
                          </React.Fragment>
                        </div>
                      </div>
                    ) : null}
                  </div>

                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__sGxl5
                    )}
                    href={"https://www.plasmic.app/"}
                  >
                    {"View Documentation"}
                  </a>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__pPuqY)}>
                  <Iframe
                    data-plasmic-name={"iframe"}
                    data-plasmic-override={overrides.iframe}
                    className={classNames("__wab_instance", sty.iframe)}
                    preview={true}
                    src={"https://dashboard.razorpay.com/"}
                  />
                </div>
              </div>
            </p.Stack>
          </ParallaxWrapper>

          <PlasmicHead
            data-plasmic-name={"head"}
            data-plasmic-override={overrides.head}
            className={classNames("__wab_instance", sty.head)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "scrollParallax",
    "img",
    "button",
    "h1",
    "signUpNowButton",
    "iframe",
    "head"
  ],

  scrollParallax: [
    "scrollParallax",
    "img",
    "button",
    "h1",
    "signUpNowButton",
    "iframe"
  ],

  img: ["img"],
  button: ["button"],
  h1: ["h1"],
  signUpNowButton: ["signUpNowButton"],
  iframe: ["iframe"],
  head: ["head"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    scrollParallax: makeNodeComponent("scrollParallax"),
    img: makeNodeComponent("img"),
    button: makeNodeComponent("button"),
    h1: makeNodeComponent("h1"),
    signUpNowButton: makeNodeComponent("signUpNowButton"),
    iframe: makeNodeComponent("iframe"),
    head: makeNodeComponent("head"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
